# Generated by Django 4.0 on 2022-05-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('photo_book', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('prices', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True)),
                ('rental_price_day', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('rental_period', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('availble', 'availble'), ('sold', 'sold'), ('rental', 'rental')], max_length=50, null=True)),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='lib_app.category')),
            ],
        ),
    ]
